//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	cdn "k8s.toms.place/apiserver/pkg/apis/cdn"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*cdn.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_File_To_cdn_File(a.(*File), b.(*cdn.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cdn.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cdn_File_To_v1alpha1_File(a.(*cdn.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileContent)(nil), (*cdn.FileContent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileContent_To_cdn_FileContent(a.(*FileContent), b.(*cdn.FileContent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cdn.FileContent)(nil), (*FileContent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cdn_FileContent_To_v1alpha1_FileContent(a.(*cdn.FileContent), b.(*FileContent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileList)(nil), (*cdn.FileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileList_To_cdn_FileList(a.(*FileList), b.(*cdn.FileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cdn.FileList)(nil), (*FileList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cdn_FileList_To_v1alpha1_FileList(a.(*cdn.FileList), b.(*FileList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSpec)(nil), (*cdn.FileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileSpec_To_cdn_FileSpec(a.(*FileSpec), b.(*cdn.FileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cdn.FileSpec)(nil), (*FileSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cdn_FileSpec_To_v1alpha1_FileSpec(a.(*cdn.FileSpec), b.(*FileSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileStatus)(nil), (*cdn.FileStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FileStatus_To_cdn_FileStatus(a.(*FileStatus), b.(*cdn.FileStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cdn.FileStatus)(nil), (*FileStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cdn_FileStatus_To_v1alpha1_FileStatus(a.(*cdn.FileStatus), b.(*FileStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_File_To_cdn_File(in *File, out *cdn.File, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FileSpec_To_cdn_FileSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FileStatus_To_cdn_FileStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_File_To_cdn_File is an autogenerated conversion function.
func Convert_v1alpha1_File_To_cdn_File(in *File, out *cdn.File, s conversion.Scope) error {
	return autoConvert_v1alpha1_File_To_cdn_File(in, out, s)
}

func autoConvert_cdn_File_To_v1alpha1_File(in *cdn.File, out *File, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cdn_FileSpec_To_v1alpha1_FileSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cdn_FileStatus_To_v1alpha1_FileStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cdn_File_To_v1alpha1_File is an autogenerated conversion function.
func Convert_cdn_File_To_v1alpha1_File(in *cdn.File, out *File, s conversion.Scope) error {
	return autoConvert_cdn_File_To_v1alpha1_File(in, out, s)
}

func autoConvert_v1alpha1_FileContent_To_cdn_FileContent(in *FileContent, out *cdn.FileContent, s conversion.Scope) error {
	out.Status = in.Status
	return nil
}

// Convert_v1alpha1_FileContent_To_cdn_FileContent is an autogenerated conversion function.
func Convert_v1alpha1_FileContent_To_cdn_FileContent(in *FileContent, out *cdn.FileContent, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileContent_To_cdn_FileContent(in, out, s)
}

func autoConvert_cdn_FileContent_To_v1alpha1_FileContent(in *cdn.FileContent, out *FileContent, s conversion.Scope) error {
	out.Status = in.Status
	return nil
}

// Convert_cdn_FileContent_To_v1alpha1_FileContent is an autogenerated conversion function.
func Convert_cdn_FileContent_To_v1alpha1_FileContent(in *cdn.FileContent, out *FileContent, s conversion.Scope) error {
	return autoConvert_cdn_FileContent_To_v1alpha1_FileContent(in, out, s)
}

func autoConvert_v1alpha1_FileList_To_cdn_FileList(in *FileList, out *cdn.FileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cdn.File)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_FileList_To_cdn_FileList is an autogenerated conversion function.
func Convert_v1alpha1_FileList_To_cdn_FileList(in *FileList, out *cdn.FileList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileList_To_cdn_FileList(in, out, s)
}

func autoConvert_cdn_FileList_To_v1alpha1_FileList(in *cdn.FileList, out *FileList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]File)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cdn_FileList_To_v1alpha1_FileList is an autogenerated conversion function.
func Convert_cdn_FileList_To_v1alpha1_FileList(in *cdn.FileList, out *FileList, s conversion.Scope) error {
	return autoConvert_cdn_FileList_To_v1alpha1_FileList(in, out, s)
}

func autoConvert_v1alpha1_FileSpec_To_cdn_FileSpec(in *FileSpec, out *cdn.FileSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.Size = in.Size
	out.ContentType = in.ContentType
	out.ResourceLocation = in.ResourceLocation
	return nil
}

// Convert_v1alpha1_FileSpec_To_cdn_FileSpec is an autogenerated conversion function.
func Convert_v1alpha1_FileSpec_To_cdn_FileSpec(in *FileSpec, out *cdn.FileSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSpec_To_cdn_FileSpec(in, out, s)
}

func autoConvert_cdn_FileSpec_To_v1alpha1_FileSpec(in *cdn.FileSpec, out *FileSpec, s conversion.Scope) error {
	out.URL = in.URL
	out.Size = in.Size
	out.ContentType = in.ContentType
	out.ResourceLocation = in.ResourceLocation
	return nil
}

// Convert_cdn_FileSpec_To_v1alpha1_FileSpec is an autogenerated conversion function.
func Convert_cdn_FileSpec_To_v1alpha1_FileSpec(in *cdn.FileSpec, out *FileSpec, s conversion.Scope) error {
	return autoConvert_cdn_FileSpec_To_v1alpha1_FileSpec(in, out, s)
}

func autoConvert_v1alpha1_FileStatus_To_cdn_FileStatus(in *FileStatus, out *cdn.FileStatus, s conversion.Scope) error {
	out.Uploaded = in.Uploaded
	out.Error = in.Error
	return nil
}

// Convert_v1alpha1_FileStatus_To_cdn_FileStatus is an autogenerated conversion function.
func Convert_v1alpha1_FileStatus_To_cdn_FileStatus(in *FileStatus, out *cdn.FileStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileStatus_To_cdn_FileStatus(in, out, s)
}

func autoConvert_cdn_FileStatus_To_v1alpha1_FileStatus(in *cdn.FileStatus, out *FileStatus, s conversion.Scope) error {
	out.Uploaded = in.Uploaded
	out.Error = in.Error
	return nil
}

// Convert_cdn_FileStatus_To_v1alpha1_FileStatus is an autogenerated conversion function.
func Convert_cdn_FileStatus_To_v1alpha1_FileStatus(in *cdn.FileStatus, out *FileStatus, s conversion.Scope) error {
	return autoConvert_cdn_FileStatus_To_v1alpha1_FileStatus(in, out, s)
}
